### PR TITLE
fix #5

### LINKED ISSUE #5: Complete configuration for each dat.
When cloning a dat there are quite a few [default options](https://github.com/datproject/dat/blob/bf714e13018c02570d2a18617ed627f53548538c/bin/cli.js#L20-L31) and even [extended options](https://github.com/datproject/dat/blob/bf714e13018c02570d2a18617ed627f53548538c/src/commands/clone.js#L9-L28). Those are useful and I think they would be very important for the daemon to work well.

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Comment by soyuka** [comment]
mhh do you see more options I should add? Some options are used for `importFiles` which is not (yet?) supported by the daemon.

**Comment by martinheidegger** [comment]
This is maybe not a complete list but `watch` _(for changes of local dats)_ comes to mind, as well as `version` to specify a certain version to download. Also `sparse` only works in combination with `selectedFiles`: 

https://github.com/datproject/dat/blob/9a7150a10a7b312d408e2c223608eaea6d21f213/src/ui/archive.js#L32

[`opts.exit`](https://github.com/datproject/dat/blob/df387ced3ae7c83261a81276cdbb3f37dbe26f54/src/ui/components/download.js#L18) allows to remove a dat from the list (daemon) once it has been completely up/downloaded. [`opts.logspeed`](https://github.com/datproject/dat/blob/1343821a2eed9189a013c22ee93e9d61a80098b1/src/lib/import-progress.js#L27) might not be super-important but it has been added for a reason maybe?

**Comment by soyuka** [comment]
logspeed is only used for neat-log (I'm not trying to rewrite dat cli)

I need to add `importFiles` before I can add the rest of these options.

**Comment by soyuka** [comment]
logspeed is only used for neat-log (I'm not trying to rewrite dat cli)

I need to add `importFiles` before I can add the rest of these options.

**Pull request closed without merging**
